version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ğŸ¤–ï¸ GH Actions "
      include: "scope"
    labels: [ "dependencies" ]
    reviewers: [ "<GH USERAME>" ]

  # Maintain dependencies for python with poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ğŸ¤–ï¸ MAIN: "
      prefix-development: "ğŸ¤–ï¸ DEV: "
      include: "scope"
    labels: [ "dependencies" ]
    reviewers: [ "<GH USERAME>" ]
