blank_issues_enabled: true
contact_links:
  - name: ğŸ™ğŸ» Support This Project
    url: https://github.com/sponsors/<GH USERNAME>
    about: Help support continued development on this project
  - name: ğŸ‘¨ğŸ»â€ğŸ’» More about the maintainer
    url: <WEBSITE>
    about: get to know the maintainer of <REPO NAME>
